# Generated by Django 2.2.6 on 2019-10-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
