# Generated by Django 2.2.6 on 2019-10-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
