# Generated by Django 2.2.6 on 2019-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('process_time', models.CharField(max_length=10)),
                ('backdrop_type', models.CharField(max_length=10)),
            ],
        ),
    ]
